require('options')
require('keymaps')
require('plugins')
require('colourscheme')
require('config.tree-sitter')
require('config.signify')
require('config.telescope')
require('config.comment')

require('config.nvim-lsp')
require('config.mason')
require('config.nvim-cmp')
require('config.cmp')
